{% set name = "jupyter-packaging" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_packaging-{{ version }}.tar.gz
  sha256: b27455d60adc93a7baa2e0b8f386be81b932bb4e3c0116046df9ed230cd3faac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
    - packaging
  run:
    - python >=3.6
    - packaging
    - tomlkit
    - setuptools >=46.4.0
    - wheel
    - deprecation

test:
  imports:
    - jupyter_packaging

about:
  home: https://github.com/jupyter/jupyter-packaging
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Packaging Utilities

  description: |
    Jupyter Packaging Utilities
  dev_url: https://github.com/jupyter/jupyter-packaging

extra:
  recipe-maintainers:
    - blink1073
    - vidartf
    - timkpaine
    - xmnlab
